[package]
name = "ytdlp-api"
version = "0.1.0"

[dependencies]
node = ">=20.0"

[command]
name = "serve"
args = ["npm", "start"]

[fs]
"/tmp" = "tmp"

[http]
routes = [
  { path = "/", proxy = "serve" }
]
